# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

github_username:  avineshpvs
github: [metadata]
minimal_mistakes_skin: default

locale                   : "en-US"
title                    : "Avinesh P.V.S"
title_separator          : "-"
subtitle                 : "NLP & ML Researcher, Adventurer and Traveler"
name                     : "Avinesh P.V.S"
description              : >-
url                      : https://avineshpvs.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "avineshpvs/avineshpvs.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "facebook" # false (default), "disqus", "discourse", "facebook", "staticman_v2", "staticman", "utterances", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                : "232522868020506"
    num_posts            : 5
    colorscheme          : "light"
  utterances:
    theme                : "github-light"
    issue_term           : "pathname"
reCaptcha:
  siteKey                : "6LdYnPAUAAAAAKW9yKUnAz_uocSRuh0asBuGsIo9"
  secret                 : "6LdYnPAUAAAAABukmAV013aVJYaukdDiR-jlCpzQ"

atom_feed:
  path                   : "http://feeds.feedburner.com/avineshpvs"

search                   : true
search_full_content      : true
search_provider          : lunr
lunr:
  files_to_exclude:
    - _posts/2017-11-28-post-exclude-search.md

# SEO Related
google_site_verification : "google-site-verification=zBUScfv4Ix-7j_6Svzf6sGeIfRSc8zECLMZbv0aGA-o"
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : &twitter "avineshpvs"
facebook:
  username               : &facebook "avineshpvs"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/site-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Person
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/avineshpvs"
    - "https://www.facebook.com/avinesh.pvs"
    - "https://instagram.com/avineshpvs"

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-2430029-2"
    anonymize_ip         : true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.19.1"

sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include:
  - _pages
  - _posts
  - blog
  - assests/css/style.scss

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

author:
  name: "Avinesh P.V.S"
  bio: "NLP & ML Research Scientist, Adventurer and Traveller"
  avatar: "/assets/portfolio.png"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:billyrick@rick.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://avineshpvs.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/avineshpvs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/avineshpvs"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/avineshpvs"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/avineshpvs"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/avineshpvs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/avineshpvs"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/avineshpvs"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/avinesh.pvs"

collections:
  docs:
    output: true
    permalink: /:collection/:path/
  recipes:
    output: true
    permalink: /:collection/:path/
  pets:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

